### ISSUE TITLE
Android - Response is the Tag Id/SerialNumber rather than the content

### ISSUE THREAD

**Issue by AcidNoX** [matteocrippa/flutter-nfc-reader#9]
Testing this on a Android device and the response appears to be the Tag Serial Number / Id rather than the content:

![image](https://user-images.githubusercontent.com/8410021/49646516-2d89d680-fa17-11e8-895d-8c78c81fea1f.png)
![screenshot_20181207-115726](https://user-images.githubusercontent.com/8410021/49646624-7f326100-fa17-11e8-96f0-63f202d93b27.jpg)
![screenshot_20181207-115732](https://user-images.githubusercontent.com/8410021/49646627-80fc2480-fa17-11e8-8044-dbe1828dd71d.jpg)

As you can see the hex code returned matches the serial number rather than the text content on the card (which is "Hello").

**Comment by matteocrippa** [comment]
I made a patch, but had no way to test that, try using the master version and see if it works

**Comment by abhisheklal04** [comment]
The latest master code doesn't works.

**Comment by CosimoSguanci** [comment]
I'm also facing this issue. It returns the serial number of the NFC Tag

**Comment by matteocrippa** [comment]
Give a try to latest in master after merge if a pr

**Comment by CosimoSguanci** [comment]
How can I use that? Now i've ^0.0.21 in my pubspec.yaml file.

**Comment by matteocrippa** [comment]
about to push`0.0.22` hope to do later this morning

**Comment by CosimoSguanci** [comment]
I tried the latest version. Now, if the text written in the tag is 'flutter!!!' I get 
`�Tenflutter!!!!` by reading it.

**Comment by kgamecarter** [comment]
I need the ID.
Can response a object with content and ID?

**Comment by matteocrippa** [comment]
@CosimoSguanci @kgamecarter give a try to this branch feature/refactor

**Comment by kgamecarter** [comment]
There is no responses when I read Mifare Classic card.
I only need Mifare Classic card ID.

**Comment by matteocrippa** [comment]
Try using debug to see if the callback has been triggered, so we can figure out how to proceed or if the callback is the bottleneck.

I have no mifare tag so no way to test by myself

**Comment by Schillen** [comment]
using refactor branch: after reading an nfc tag type "nxp mifare classic" the app displays

Status: NFCStatus.none
Identifier : questionmark-icon + random letters
Content:
Error:

**Comment by gavinerasmus** [comment]
I receive the NFC ID on a Samsung Galaxy S6 when using version 0.21. I created a new project, copied across the code and used v0.22 and got no response from the reader. I'm going to do some investigating and see what I can figure our and will let you know. v0.21 is great - thanks for creating it!

**Comment by matteocrippa** [comment]
up is now the `master` working fine?

**Comment by CosimoSguanci** [comment]
For me yes, it works except from the empty ID that i get on iOS (i opened another issue)

**Comment by crzdg** [comment]
Hi there,

I'm using the package since today. I was able to set up a reader in my scoped_model based app. I'm also get the my cards content. However, the information in the bytes before the payload is broken. My message should be:

urn:nfc:ext:app.io:IDid12345

The string I get is somehow broken and only show the payload properly. It would have been easy for me to split the string and extract the values out of it, as I'm defining my NDEFMessages. 

However, I used the NFC technology now heavily in one of my projects. I do have some basic knowledge about NFC and NDEF. A nice documented NFCReader project with is implementing and explaining the NDEF Format is found here:

https://nfcpy.readthedocs.io/en/latest/
NDEF Docu: https://nfcpy.readthedocs.io/en/latest/topics/ndef.html

About the formats. The NDEF Format is as you may know the open NFC format. If you want to read seperate formats you have to respectively handle the byte code. If you want to get more information feel free to contact me for a skype call or somewhat.

**Comment by crzdg** [comment]
String is somehow false encode. Would be nice if it would encode after NDEF Format. Good resources are found here.

https://nfcpy.readthedocs.io/en/latest/topics/ndef.html
https://nfcpy.readthedocs.io/en/latest/overview.html

**Comment by matteocrippa** [comment]
@crzdg create a new dedicated issue, if you can provide also some debug info (eg. expected result, result obtained it could help more.

I will close this because it seems to work now for id/serial, if issue is still open, re-open the task
